logging:
  level:
    root: INFO

amazon:
  associateId: vonzhou

management:
  security:
    enabled: false
---

spring:
  profiles: dev

logging:
  level:
    root: DEBUG

---

spring:
  profiles: prod
logging:
  level:
    root: WARN




